# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: self-hosted
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2.3.1
        with:
          python-version: 3.7.1
          cache: pip
      - run: pip install -r requirements.txt
      - run: pip install https://github.com/waivek/python_common/archive/master.zip
      - name: Run a one-line script
        run: python print_date.py
