# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: self-hosted
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: python print_date.py
