
# This is a basic workflow to help you get started with Actions

name: CRON

on:
  schedule:
      - cron: '*/5 * * * *'
jobs:
  cronjob:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2.3.1
        with:
          python-version: 3.7.1
          cache: pip
      - run: pip install -r requirements.txt
      - run: pip install https://github.com/waivek/python_common/archive/master.zip
      - uses: actions/checkout@v2
      - name: Run CRON Job
        run: python run_cron.py
