
# This is a basic workflow to help you get started with Actions

name: CRON

on:
  schedule:
      - cron: '39 17 * * *'
jobs:
  cronjob:
    runs-on: self-hosted
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Run CRON Job
        run: python run_cron.py
