
name: TestUpsert

on:
  workflow_dispatch:
jobs:
  testupsert:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2.3.1
        with:
          python-version: 3.9.1
          cache: pip
      - uses: actions/checkout@v2
      - name: Test Upsert
        run: python test_upsert.py
