
name: PythonUpsert

on:
  workflow_dispatch:
jobs:
  pythonupsert:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2.3.1
        with:
          python-version: 3.7.1
          cache: pip
      - name: Python Upsert
        run: python test_upsert.py
